name: hemend_toolkit
description: Hemend projects toolkit that provides basic environments for Hemend
  core package
version: 1.0.0
environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  bloc: ^8.0.3
  cli_util: ^0.3.5
  json2yaml: ^3.0.0
  meta: ^1.8.0
  yaml: ^3.1.1
