name: hemend_toolkit
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  bloc: ^8.0.3
  cli_util: ^0.3.5
  meta: ^1.8.0
