name: hemend_toolkit
description: Hemend projects toolkit that provides basic environments for Hemend core package
version: 1.0.2+1
publish_to: none
executables: 
  hem: hemend_toolkit
environment: 
  sdk: '>=2.17.3 <3.0.0'
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  args: ^2.3.1
  crypto: ^3.0.2
  cli_util: ^0.3.5
  http: ^0.13.4
  json2yaml: ^3.0.0
  meta: ^1.7.0
  yaml: ^3.1.1
  dio: ^4.0.6
  path: ^1.8.2
  yaml_modify: ^1.0.1
