name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cp . /tmp/toolkit -r
      - run: ls >> /tmp/pwres.log
